version: '3'
services:

    mysql:
        image: mysql:5.7
        volumes:
            - mysql:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: changeme
            MYSQL_DATABASE: timeshite
            MYSQL_USER: timeshite
            MYSQL_PASSWORD: timeshite
        restart: unless-stopped


    timeshite:
        build: .
        ports:
            - 8888:8888
        volumes:
            - .:/opt/drupal/web/modules/custom/timesheet
            - files:/opt/drupal/web/sites/default/files
        restart: always
        links:
            - mysql

volumes:
    mysql:
    files:
