version: '3'
services:

    timeshite:
        build: .
        ports:
            - 8888:8888
        volumes:
            - .:/opt/drupal/web/modules/custom/timesheet
              # - ./drupal.sqlite:/opt/drupal/web/sites/default/files/.ht.sqlite
        restart: always
