<?php

/**
 * @file
 * Contains timesheet.module.
 */
use Drupal\Core\Routing\RouteMatchInterface;

// http://127.0.0.1:8888/node/add/time_sheet_entry?project=UMM8sQwK/neontribe-internal-projects&uuid=9DpXF2bz

/**
 * Implements hook_form_FORM_ID_alter().
 */
function timesheet_form_node_time_sheet_entry_form_alter(&$form, &$form_state, $form_id) {
  dpm($form_id, 'formid');
  $project = \Drupal::request()->request->get('project');
  $uuid = \Drupal::request()->request->get('uuid');

  $user = \Drupal\user\Entity\User::load(\Drupal::currentUser()->id());

  $service = \Drupal::service("timesheet.default");

  $form['field_user']['widget'][0]['target_id']['#default_value'] = $user;
  // $form['field_issue_uuid']['widget'][0]['value']['#default_value'] = $uuid;
}

/**
 * Implements hook_help().
 */
function timesheet_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the timesheet module.
    case 'help.page.timesheet':
      $output = '';
      $output .= '<h3>About</h3>';
      $output .= '<p>Neontribe time sheeting</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function timesheet_theme() {
  return [
    'timesheet' => [
      'render element' => 'children'
    ]
  ];
}
